//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Best_ResourceMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Best.ResourceMgr), typeof(System.Object));
		L.RegFunction("Initialize", Initialize);
		L.RegFunction("UnInitialize", UnInitialize);
		L.RegFunction("LoadConfig", LoadConfig);
		L.RegFunction("LoadTextureSync", LoadTextureSync);
		L.RegFunction("LoadImmortalTextureSync", LoadImmortalTextureSync);
		L.RegFunction("LoadAtlasSync", LoadAtlasSync);
		L.RegFunction("LoadNormalObjSync", LoadNormalObjSync);
		L.RegFunction("LoadSceneResidentMemoryObjSync", LoadSceneResidentMemoryObjSync);
		L.RegFunction("LoadResidentMemoryObjSync", LoadResidentMemoryObjSync);
		L.RegFunction("LoadNormalObjAsync", LoadNormalObjAsync);
		L.RegFunction("LoadSceneResidentMemoryObjAsync", LoadSceneResidentMemoryObjAsync);
		L.RegFunction("LoadResidentMemoryObjAsync", LoadResidentMemoryObjAsync);
		L.RegFunction("LoadSceneAsync", LoadSceneAsync);
		L.RegFunction("UnloadLastSceneAsset", UnloadLastSceneAsset);
		L.RegFunction("UnloadResource", UnloadResource);
		L.RegFunction("UnloadImmortalResource", UnloadImmortalResource);
		L.RegFunction("UnloadAllNormalResources", UnloadAllNormalResources);
		L.RegFunction("DebugBundleNum", DebugBundleNum);
		L.RegFunction("DebugAllBundle", DebugAllBundle);
		L.RegFunction("New", _CreateBest_ResourceMgr);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateBest_ResourceMgr(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Best.ResourceMgr obj = new Best.ResourceMgr();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Best.ResourceMgr.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Initialize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Best.ResourceMgr obj = (Best.ResourceMgr)ToLua.CheckObject(L, 1, typeof(Best.ResourceMgr));
			obj.Initialize();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnInitialize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Best.ResourceMgr obj = (Best.ResourceMgr)ToLua.CheckObject(L, 1, typeof(Best.ResourceMgr));
			obj.UnInitialize();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadConfig(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Best.ResourceMgr obj = (Best.ResourceMgr)ToLua.CheckObject(L, 1, typeof(Best.ResourceMgr));
			obj.LoadConfig();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadTextureSync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Best.ResourceMgr obj = (Best.ResourceMgr)ToLua.CheckObject(L, 1, typeof(Best.ResourceMgr));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.Texture2D o = obj.LoadTextureSync(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadImmortalTextureSync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Best.ResourceMgr obj = (Best.ResourceMgr)ToLua.CheckObject(L, 1, typeof(Best.ResourceMgr));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.Texture2D o = obj.LoadImmortalTextureSync(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadAtlasSync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Best.ResourceMgr obj = (Best.ResourceMgr)ToLua.CheckObject(L, 1, typeof(Best.ResourceMgr));
			string arg0 = ToLua.CheckString(L, 2);
			UIAtlas o = obj.LoadAtlasSync(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadNormalObjSync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Best.ResourceMgr obj = (Best.ResourceMgr)ToLua.CheckObject(L, 1, typeof(Best.ResourceMgr));
			AssetBundleParams arg0 = (AssetBundleParams)ToLua.CheckObject(L, 2, typeof(AssetBundleParams));
			UnityEngine.Object o = obj.LoadNormalObjSync(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadSceneResidentMemoryObjSync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Best.ResourceMgr obj = (Best.ResourceMgr)ToLua.CheckObject(L, 1, typeof(Best.ResourceMgr));
			AssetBundleParams arg0 = (AssetBundleParams)ToLua.CheckObject(L, 2, typeof(AssetBundleParams));
			UnityEngine.Object o = obj.LoadSceneResidentMemoryObjSync(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadResidentMemoryObjSync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Best.ResourceMgr obj = (Best.ResourceMgr)ToLua.CheckObject(L, 1, typeof(Best.ResourceMgr));
			AssetBundleParams arg0 = (AssetBundleParams)ToLua.CheckObject(L, 2, typeof(AssetBundleParams));
			UnityEngine.Object o = obj.LoadResidentMemoryObjSync(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadNormalObjAsync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Best.ResourceMgr obj = (Best.ResourceMgr)ToLua.CheckObject(L, 1, typeof(Best.ResourceMgr));
			AssetBundleParams arg0 = (AssetBundleParams)ToLua.CheckObject(L, 2, typeof(AssetBundleParams));
			Best.AssetBundleInfo.LoadAssetCompleteHandler arg1 = null;
			LuaTypes funcType3 = LuaDLL.lua_type(L, 3);

			if (funcType3 != LuaTypes.LUA_TFUNCTION)
			{
				 arg1 = (Best.AssetBundleInfo.LoadAssetCompleteHandler)ToLua.CheckObject(L, 3, typeof(Best.AssetBundleInfo.LoadAssetCompleteHandler));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 3);
				arg1 = DelegateFactory.CreateDelegate(typeof(Best.AssetBundleInfo.LoadAssetCompleteHandler), func) as Best.AssetBundleInfo.LoadAssetCompleteHandler;
			}

			obj.LoadNormalObjAsync(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadSceneResidentMemoryObjAsync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Best.ResourceMgr obj = (Best.ResourceMgr)ToLua.CheckObject(L, 1, typeof(Best.ResourceMgr));
			AssetBundleParams arg0 = (AssetBundleParams)ToLua.CheckObject(L, 2, typeof(AssetBundleParams));
			Best.AssetBundleInfo.LoadAssetCompleteHandler arg1 = null;
			LuaTypes funcType3 = LuaDLL.lua_type(L, 3);

			if (funcType3 != LuaTypes.LUA_TFUNCTION)
			{
				 arg1 = (Best.AssetBundleInfo.LoadAssetCompleteHandler)ToLua.CheckObject(L, 3, typeof(Best.AssetBundleInfo.LoadAssetCompleteHandler));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 3);
				arg1 = DelegateFactory.CreateDelegate(typeof(Best.AssetBundleInfo.LoadAssetCompleteHandler), func) as Best.AssetBundleInfo.LoadAssetCompleteHandler;
			}

			obj.LoadSceneResidentMemoryObjAsync(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadResidentMemoryObjAsync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Best.ResourceMgr obj = (Best.ResourceMgr)ToLua.CheckObject(L, 1, typeof(Best.ResourceMgr));
			AssetBundleParams arg0 = (AssetBundleParams)ToLua.CheckObject(L, 2, typeof(AssetBundleParams));
			Best.AssetBundleInfo.LoadAssetCompleteHandler arg1 = null;
			LuaTypes funcType3 = LuaDLL.lua_type(L, 3);

			if (funcType3 != LuaTypes.LUA_TFUNCTION)
			{
				 arg1 = (Best.AssetBundleInfo.LoadAssetCompleteHandler)ToLua.CheckObject(L, 3, typeof(Best.AssetBundleInfo.LoadAssetCompleteHandler));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 3);
				arg1 = DelegateFactory.CreateDelegate(typeof(Best.AssetBundleInfo.LoadAssetCompleteHandler), func) as Best.AssetBundleInfo.LoadAssetCompleteHandler;
			}

			obj.LoadResidentMemoryObjAsync(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadSceneAsync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Best.ResourceMgr obj = (Best.ResourceMgr)ToLua.CheckObject(L, 1, typeof(Best.ResourceMgr));
			string arg0 = ToLua.CheckString(L, 2);
			Best.SceneLoadedCallback arg1 = null;
			LuaTypes funcType3 = LuaDLL.lua_type(L, 3);

			if (funcType3 != LuaTypes.LUA_TFUNCTION)
			{
				 arg1 = (Best.SceneLoadedCallback)ToLua.CheckObject(L, 3, typeof(Best.SceneLoadedCallback));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 3);
				arg1 = DelegateFactory.CreateDelegate(typeof(Best.SceneLoadedCallback), func) as Best.SceneLoadedCallback;
			}

			obj.LoadSceneAsync(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnloadLastSceneAsset(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Best.ResourceMgr obj = (Best.ResourceMgr)ToLua.CheckObject(L, 1, typeof(Best.ResourceMgr));
			string arg0 = ToLua.CheckString(L, 2);
			obj.UnloadLastSceneAsset(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnloadResource(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Best.ResourceMgr obj = (Best.ResourceMgr)ToLua.CheckObject(L, 1, typeof(Best.ResourceMgr));
			string arg0 = ToLua.CheckString(L, 2);
			System.Type arg1 = (System.Type)ToLua.CheckObject(L, 3, typeof(System.Type));
			bool o = obj.UnloadResource(arg0, arg1);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnloadImmortalResource(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Best.ResourceMgr obj = (Best.ResourceMgr)ToLua.CheckObject(L, 1, typeof(Best.ResourceMgr));
			string arg0 = ToLua.CheckString(L, 2);
			System.Type arg1 = (System.Type)ToLua.CheckObject(L, 3, typeof(System.Type));
			bool o = obj.UnloadImmortalResource(arg0, arg1);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnloadAllNormalResources(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Best.ResourceMgr obj = (Best.ResourceMgr)ToLua.CheckObject(L, 1, typeof(Best.ResourceMgr));
			obj.UnloadAllNormalResources();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DebugBundleNum(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Best.ResourceMgr obj = (Best.ResourceMgr)ToLua.CheckObject(L, 1, typeof(Best.ResourceMgr));
			string arg0 = ToLua.CheckString(L, 2);
			obj.DebugBundleNum(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DebugAllBundle(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Best.ResourceMgr obj = (Best.ResourceMgr)ToLua.CheckObject(L, 1, typeof(Best.ResourceMgr));
			obj.DebugAllBundle();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

