//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Framework_GameKernelWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Framework.GameKernel), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("CreateGameKernel", CreateGameKernel);
		L.RegFunction("Shutdown", Shutdown);
		L.RegFunction("GetResourceMgr", GetResourceMgr);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateGameKernel(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			Framework.GameKernel.CreateGameKernel();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Shutdown(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			Framework.GameKernel.Shutdown();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetResourceMgr(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			Best.ResourceMgr o = Framework.GameKernel.GetResourceMgr();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

