//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ProtobufDataConfig_ProtobufDataConfigMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ProtobufDataConfig.ProtobufDataConfigMgr), typeof(System.Object));
		L.RegFunction("Clear", Clear);
		L.RegFunction("ReadConfigDataToLua", ReadConfigDataToLua);
		L.RegFunction("New", _CreateProtobufDataConfig_ProtobufDataConfigMgr);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateProtobufDataConfig_ProtobufDataConfigMgr(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ProtobufDataConfig.ProtobufDataConfigMgr obj = new ProtobufDataConfig.ProtobufDataConfigMgr();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ProtobufDataConfig.ProtobufDataConfigMgr.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			ProtobufDataConfig.ProtobufDataConfigMgr.Clear();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReadConfigDataToLua(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			LuaInterface.LuaByteBuffer o = ProtobufDataConfig.ProtobufDataConfigMgr.ReadConfigDataToLua(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

