//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_tablemodetwo.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TableModeTwo")]
  public partial class TableModeTwo : global::ProtoBuf.IExtensible
  {
    public TableModeTwo() {}
    
    private uint _PlayerLevel;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PlayerLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PlayerLevel
    {
      get { return _PlayerLevel; }
      set { _PlayerLevel = value; }
    }
    private uint _StrengthenLimit;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"StrengthenLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint StrengthenLimit
    {
      get { return _StrengthenLimit; }
      set { _StrengthenLimit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TableModeTwoArray")]
  public partial class TableModeTwoArray : global::ProtoBuf.IExtensible
  {
    public TableModeTwoArray() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.TableModeTwo> _items = new global::System.Collections.Generic.List<dataconfig.TableModeTwo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.TableModeTwo> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}