-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"


local TABLEMODEONE = protobuf.Descriptor();
local TABLEMODEONE_INTERNALTYPE_ADDATTRINFO = protobuf.Descriptor();
local TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_KEY_FIELD = protobuf.FieldDescriptor();
local TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_VALUE_FIELD = protobuf.FieldDescriptor();
local TABLEMODEONE_PARAONE_FIELD = protobuf.FieldDescriptor();
local TABLEMODEONE_PARATWO_FIELD = protobuf.FieldDescriptor();
local TABLEMODEONE_ADDATTRINFO_FIELD = protobuf.FieldDescriptor();
local TABLEMODEONEARRAY = protobuf.Descriptor();
local TABLEMODEONEARRAY_ITEMS_FIELD = protobuf.FieldDescriptor();

TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_KEY_FIELD.name = "key"
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_KEY_FIELD.full_name = ".dataconfig.TableModeOne.InternalType_AddAttrInfo.key"
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_KEY_FIELD.number = 1
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_KEY_FIELD.index = 0
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_KEY_FIELD.label = 1
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_KEY_FIELD.has_default_value = true
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_KEY_FIELD.default_value = 0
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_KEY_FIELD.type = 13
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_KEY_FIELD.cpp_type = 3

TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_VALUE_FIELD.name = "value"
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_VALUE_FIELD.full_name = ".dataconfig.TableModeOne.InternalType_AddAttrInfo.value"
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_VALUE_FIELD.number = 2
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_VALUE_FIELD.index = 1
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_VALUE_FIELD.label = 1
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_VALUE_FIELD.has_default_value = true
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_VALUE_FIELD.default_value = 0
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_VALUE_FIELD.type = 13
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_VALUE_FIELD.cpp_type = 3

TABLEMODEONE_INTERNALTYPE_ADDATTRINFO.name = "InternalType_AddAttrInfo"
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO.full_name = ".dataconfig.TableModeOne.InternalType_AddAttrInfo"
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO.nested_types = {}
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO.enum_types = {}
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO.fields = {TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_KEY_FIELD, TABLEMODEONE_INTERNALTYPE_ADDATTRINFO_VALUE_FIELD}
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO.is_extendable = false
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO.extensions = {}
TABLEMODEONE_INTERNALTYPE_ADDATTRINFO.containing_type = TABLEMODEONE
TABLEMODEONE_PARAONE_FIELD.name = "ParaOne"
TABLEMODEONE_PARAONE_FIELD.full_name = ".dataconfig.TableModeOne.ParaOne"
TABLEMODEONE_PARAONE_FIELD.number = 1
TABLEMODEONE_PARAONE_FIELD.index = 0
TABLEMODEONE_PARAONE_FIELD.label = 2
TABLEMODEONE_PARAONE_FIELD.has_default_value = true
TABLEMODEONE_PARAONE_FIELD.default_value = 0
TABLEMODEONE_PARAONE_FIELD.type = 13
TABLEMODEONE_PARAONE_FIELD.cpp_type = 3

TABLEMODEONE_PARATWO_FIELD.name = "ParaTwo"
TABLEMODEONE_PARATWO_FIELD.full_name = ".dataconfig.TableModeOne.ParaTwo"
TABLEMODEONE_PARATWO_FIELD.number = 2
TABLEMODEONE_PARATWO_FIELD.index = 1
TABLEMODEONE_PARATWO_FIELD.label = 2
TABLEMODEONE_PARATWO_FIELD.has_default_value = true
TABLEMODEONE_PARATWO_FIELD.default_value = 0
TABLEMODEONE_PARATWO_FIELD.type = 13
TABLEMODEONE_PARATWO_FIELD.cpp_type = 3

TABLEMODEONE_ADDATTRINFO_FIELD.name = "AddAttrInfo"
TABLEMODEONE_ADDATTRINFO_FIELD.full_name = ".dataconfig.TableModeOne.AddAttrInfo"
TABLEMODEONE_ADDATTRINFO_FIELD.number = 3
TABLEMODEONE_ADDATTRINFO_FIELD.index = 2
TABLEMODEONE_ADDATTRINFO_FIELD.label = 3
TABLEMODEONE_ADDATTRINFO_FIELD.has_default_value = false
TABLEMODEONE_ADDATTRINFO_FIELD.default_value = {}
TABLEMODEONE_ADDATTRINFO_FIELD.message_type = TABLEMODEONE_INTERNALTYPE_ADDATTRINFO
TABLEMODEONE_ADDATTRINFO_FIELD.type = 11
TABLEMODEONE_ADDATTRINFO_FIELD.cpp_type = 10

TABLEMODEONE.name = "TableModeOne"
TABLEMODEONE.full_name = ".dataconfig.TableModeOne"
TABLEMODEONE.nested_types = {TABLEMODEONE_INTERNALTYPE_ADDATTRINFO}
TABLEMODEONE.enum_types = {}
TABLEMODEONE.fields = {TABLEMODEONE_PARAONE_FIELD, TABLEMODEONE_PARATWO_FIELD, TABLEMODEONE_ADDATTRINFO_FIELD}
TABLEMODEONE.is_extendable = false
TABLEMODEONE.extensions = {}
TABLEMODEONEARRAY_ITEMS_FIELD.name = "items"
TABLEMODEONEARRAY_ITEMS_FIELD.full_name = ".dataconfig.TableModeOneArray.items"
TABLEMODEONEARRAY_ITEMS_FIELD.number = 1
TABLEMODEONEARRAY_ITEMS_FIELD.index = 0
TABLEMODEONEARRAY_ITEMS_FIELD.label = 3
TABLEMODEONEARRAY_ITEMS_FIELD.has_default_value = false
TABLEMODEONEARRAY_ITEMS_FIELD.default_value = {}
TABLEMODEONEARRAY_ITEMS_FIELD.message_type = TABLEMODEONE
TABLEMODEONEARRAY_ITEMS_FIELD.type = 11
TABLEMODEONEARRAY_ITEMS_FIELD.cpp_type = 10

TABLEMODEONEARRAY.name = "TableModeOneArray"
TABLEMODEONEARRAY.full_name = ".dataconfig.TableModeOneArray"
TABLEMODEONEARRAY.nested_types = {}
TABLEMODEONEARRAY.enum_types = {}
TABLEMODEONEARRAY.fields = {TABLEMODEONEARRAY_ITEMS_FIELD}
TABLEMODEONEARRAY.is_extendable = false
TABLEMODEONEARRAY.extensions = {}

TableModeOne = protobuf.Message(TABLEMODEONE)
TableModeOne.InternalType_AddAttrInfo = protobuf.Message(TABLEMODEONE_INTERNALTYPE_ADDATTRINFO)
TableModeOneArray = protobuf.Message(TABLEMODEONEARRAY)

--[[Another parser, for the memory reason, use plain table struct 
instead of protobuf table! Auto generated, do not edit!!]]
tablemodeone_x = {}
tablemodeone_x.__index = tablemodeone_x


--[[The class create method]]
function tablemodeone_x.New()
    local self = {}
    setmetatable(self, tablemodeone_x)
    self.items = {}
    return self
end


--[[The data parse method, input the protobuf data instance]]
function tablemodeone_x:ParseData(protobufData)
    for k, v in ipairs(protobufData.items) do 
        local item = {}
        item.ParaOne = v.ParaOne
        item.ParaTwo = v.ParaTwo
        item.AddAttrInfo = {}
        local subItems_0 = item.AddAttrInfo
        for i_0,j_0 in ipairs(v.AddAttrInfo) do
            local subItem_0 = {}
            subItem_0.key = j_0.key
            subItem_0.value = j_0.value
            table.insert(subItems_0, subItem_0)
        end
        table.insert(self.items, item)
    end
end


--[[Get the protobuf instance]]
function tablemodeone_x:GetProtobuf()
    return TableModeOneArray()
end
