-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"


local TABLEMODETWO = protobuf.Descriptor();
local TABLEMODETWO_PARAONE_FIELD = protobuf.FieldDescriptor();
local TABLEMODETWO_PARATWO_FIELD = protobuf.FieldDescriptor();
local TABLEMODETWOARRAY = protobuf.Descriptor();
local TABLEMODETWOARRAY_ITEMS_FIELD = protobuf.FieldDescriptor();

TABLEMODETWO_PARAONE_FIELD.name = "ParaOne"
TABLEMODETWO_PARAONE_FIELD.full_name = ".dataconfig.TableModeTwo.ParaOne"
TABLEMODETWO_PARAONE_FIELD.number = 1
TABLEMODETWO_PARAONE_FIELD.index = 0
TABLEMODETWO_PARAONE_FIELD.label = 2
TABLEMODETWO_PARAONE_FIELD.has_default_value = true
TABLEMODETWO_PARAONE_FIELD.default_value = 0
TABLEMODETWO_PARAONE_FIELD.type = 13
TABLEMODETWO_PARAONE_FIELD.cpp_type = 3

TABLEMODETWO_PARATWO_FIELD.name = "ParaTwo"
TABLEMODETWO_PARATWO_FIELD.full_name = ".dataconfig.TableModeTwo.ParaTwo"
TABLEMODETWO_PARATWO_FIELD.number = 2
TABLEMODETWO_PARATWO_FIELD.index = 1
TABLEMODETWO_PARATWO_FIELD.label = 2
TABLEMODETWO_PARATWO_FIELD.has_default_value = true
TABLEMODETWO_PARATWO_FIELD.default_value = 0
TABLEMODETWO_PARATWO_FIELD.type = 13
TABLEMODETWO_PARATWO_FIELD.cpp_type = 3

TABLEMODETWO.name = "TableModeTwo"
TABLEMODETWO.full_name = ".dataconfig.TableModeTwo"
TABLEMODETWO.nested_types = {}
TABLEMODETWO.enum_types = {}
TABLEMODETWO.fields = {TABLEMODETWO_PARAONE_FIELD, TABLEMODETWO_PARATWO_FIELD}
TABLEMODETWO.is_extendable = false
TABLEMODETWO.extensions = {}
TABLEMODETWOARRAY_ITEMS_FIELD.name = "items"
TABLEMODETWOARRAY_ITEMS_FIELD.full_name = ".dataconfig.TableModeTwoArray.items"
TABLEMODETWOARRAY_ITEMS_FIELD.number = 1
TABLEMODETWOARRAY_ITEMS_FIELD.index = 0
TABLEMODETWOARRAY_ITEMS_FIELD.label = 3
TABLEMODETWOARRAY_ITEMS_FIELD.has_default_value = false
TABLEMODETWOARRAY_ITEMS_FIELD.default_value = {}
TABLEMODETWOARRAY_ITEMS_FIELD.message_type = TABLEMODETWO
TABLEMODETWOARRAY_ITEMS_FIELD.type = 11
TABLEMODETWOARRAY_ITEMS_FIELD.cpp_type = 10

TABLEMODETWOARRAY.name = "TableModeTwoArray"
TABLEMODETWOARRAY.full_name = ".dataconfig.TableModeTwoArray"
TABLEMODETWOARRAY.nested_types = {}
TABLEMODETWOARRAY.enum_types = {}
TABLEMODETWOARRAY.fields = {TABLEMODETWOARRAY_ITEMS_FIELD}
TABLEMODETWOARRAY.is_extendable = false
TABLEMODETWOARRAY.extensions = {}

TableModeTwo = protobuf.Message(TABLEMODETWO)
TableModeTwoArray = protobuf.Message(TABLEMODETWOARRAY)

--[[Another parser, for the memory reason, use plain table struct 
instead of protobuf table! Auto generated, do not edit!!]]
tablemodetwo_x = {}
tablemodetwo_x.__index = tablemodetwo_x


--[[The class create method]]
function tablemodetwo_x.New()
    local self = {}
    setmetatable(self, tablemodetwo_x)
    self.items = {}
    return self
end


--[[The data parse method, input the protobuf data instance]]
function tablemodetwo_x:ParseData(protobufData)
    for k, v in ipairs(protobufData.items) do 
        local item = {}
        item.ParaOne = v.ParaOne
        item.ParaTwo = v.ParaTwo
        table.insert(self.items, item)
    end
end


--[[Get the protobuf instance]]
function tablemodetwo_x:GetProtobuf()
    return TableModeTwoArray()
end
